src/BlogBundle/Entity/Category.php
<?php

namespace BlogBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
/**
 * Category
 *
 * @ORM\Table(name="categories")
 * @ORM\Entity
 */
class Category
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="SEQUENCE")
     * @ORM\SequenceGenerator(sequenceName="categories_id_seq", allocationSize=1, initialValue=1)
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=255, nullable=true)
     */
    private $name;

    /**
     * @var string
     *
     * @ORM\Column(name="description", type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\OneToMany(targetEntity="Entry", mappedBy="category",cascade={"persist"})
     */
    protected $entry;

    public function __construct()
    {
        $this->entry = new ArrayCollection();
    }

    public function  __toString()
    {
     return $this->name;   // TODO: Implement __toString() method.
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     *
     * @return Category
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set description
     *
     * @param string $description
     *
     * @return Category
     */
    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Get description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    public function getEntries(){
        return $this->entry;
    }
}

src/BlogBundle/Form/CategoryType.php
<?php

namespace BlogBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;


class CategoryType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name',TextType::class,array('label'=>'Nombre','required'=>'required',
                'attr'=>array('class'=>'form-name form-control')))
            ->add('description',TextareaType::class,array('label'=>'Descripcion','required'=>'required',
                'attr'=>array('class'=>'form-name form-control')))
            ->add('Gurdar',SubmitType::class,array(
                'attr'=>array('class'=>'form-submit btn btn-success')))
        ;
    }
    
    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'BlogBundle\Entity\Category'
        ));
    }
}

src/BlogBundle/Controller/CategoryController.php
<?php
/**
 * Created by PhpStorm.
 * User: root
 * Date: 13/11/17
 * Time: 10:32
 */

namespace BlogBundle\Controller;

use BlogBundle\Entity;
use BlogBundle\Entity\Category;
use BlogBundle\Form\CategoryType;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Component\HttpFoundation\Session\Session;
use Doctrine\Common\Collections\ArrayCollection;

class CategoryController extends Controller{

    private $session;

    public function __construct(){
        $this->session= new Session();
    }

    /**
     * @Route("/category/index", name="blog_index_category")
     */
    public function indexAction(){
        $em = $this->getDoctrine()->getEntityManager();
        $category_repo = $em->getRepository('BlogBundle:Category');
        $categories = $category_repo->findAll();

        return $this->render("BlogBundle:Category:index.html.twig", array(
            "categories" => $categories
        ));
    }

    /**
     * @Route("/category/add", name="blog_add_category")
     */
    public function addAction(Request $request){
        $category= new Category();
        $form = $this->createForm(CategoryType::class,$category);

        $form->handleRequest($request);

        if ($form->isSubmitted()){
            if($form->isValid()){
                $em = $this->getDoctrine()->getEntityManager();

                $category = new Category();
                $category->setName($form->get('name')->getData());
                $category->setDescription($form->get('description')->getData());

                $em->persist($category);
                $flush = $em->flush();

                if($flush==null){
                    $status="La etiqueta se a editado correctamente";
                }else{
                    $status="Error al editar la etiqueta";
                }
            }else{
                $status="La etiqueta no se ha editado, porque el formulario no es valido";
            }
            $this->session->getFlashBag()->add('status',$status);
            return $this->redirectToRoute('blog_index_category');
        }

        return $this->render("BlogBundle:Category:add.html.twig", array(
            "form" => $form->createView()
        ));
    }

    /**
     * @Route ("category/delete/{id}",name="blog_delete_category")
     */
    public function deleteAction($id){
        $em = $this->getDoctrine()->getEntityManager();
        $category_repo = $em->getRepository('BlogBundle:Category');
        $category = $category_repo->find($id);
        if(count($category->getEntries())==0){
            $em->remove($category);
            $em->flush();
        }
        return $this->redirectToRoute('blog_index_category');
    }

    /**
     * @Route("category/edit/{id}",name="blog_edit_category")
     */
    public function editAction(Request $request,$id){
        $em = $this->getDoctrine()->getEntityManager();
        $category_repo = $em->getRepository('BlogBundle:Category');
        $category = $category_repo->find($id);

        $form = $this->createForm(CategoryType::class,$category);

        $form->handleRequest($request);

        if ($form->isSubmitted()){
            if($form->isValid()){
                $category->setName($form->get('name')->getData());
                $category->setDescription($form->get('description')->getData());

                $em->persist($category);
                $flush = $em->flush();

                if($flush==null){
                    $status="La etiqueta se a creado correctamente";
                }else{
                    $status="Error al añadir la etiqueta";
                }
            }else{
                $status="la etiqueta no se ha creado, porque el formulario no es valido";
            }
            $this->session->getFlashBag()->add('status',$status);
            return $this->redirectToRoute('blog_index_category');
        }

        return $this->render("BlogBundle:Category:edit.html.twig", array(
            "form" => $form->createView()
        ));
    }


}

src/BlogBundle/Resources/views/Category/add.html.twig
{% extends "BlogBundle::layout.html.twig" %}

{% block content %}
    <div class="col-lg-5">
        <h2>Añadir Categorias</h2>
        {{ form_start(form) }}
        {{ form_end(form) }}
    </div>
    <div class="clear-fix"></div>

{% endblock %}

src/BlogBundle/Resources/views/Category/edit.html.twig
{% extends "BlogBundle::layout.html.twig" %}

{% block content %}
    <div class="col-lg-5">
        <h2>Editar Categorias</h2>
        {{ form_start(form) }}
        {{ form_end(form) }}
    </div>
    <div class="clear-fix"></div>

{% endblock %}

src/BlogBundle/Resources/views/Category/index.html.twig
{% extends "BlogBundle::layout.html.twig" %}

{% block content %}
    <div class="col-lg-5">
        <h2>Lista de Categorias</h2>
        <hr>
        <a href="{{ path('blog_add_category') }}" class="btn btn-success">Añadir Categorias</a>
        <hr>
        {% for message in app.session.flashbag().get('status') %}
            <div class="alert alert-success">{{ message }}</div>
        {% endfor %}
        <table class="table table-bordered">
            <tr>
                <th>Nombre</th>
                <th>Descripción</th>
                <th>Eliminar</th>
            </tr>
        {% for category in categories %}
            <tr>
                <td>{{ category.name }}</td>
                <td>{{ category.description }}</td>
                <td><a href="{{ path('blog_edit_category',{"id":category.id}) }}" class="btn btn-warning">Editar</a></td>
                <td>
                {% if category.entries|length ==0 %}
                    <a href="{{ path('blog_delete_category',{"id":category.id}) }}" class="btn btn-danger">Eliminar</a>
                {% else %}
                    Categoriia en uso
                {% endif %}
                </td>
            </tr>
        {% endfor %}
        </table>
    </div>
    <div class="clear-fix"></div>

{% endblock %}

src/BlogBundle/Resources/views/Category/menu.categories.html.twig
{% for category in categories %}
    <li><a href="#">{{ category.name }}</a></li>
{% endfor %}